from pathlib import Path

CAP = Path("src/product_intelligence/price_source_capabilities.py")
WORK = Path("src/product_intelligence/price_workflow.py")

cap = CAP.read_text(encoding="utf-8")
method_anchor = '''    def direct_candidates(\n'''
method = '''    def provider_fallback_domains(\n        self,\n        identity: ProductIdentity,\n        *,\n        limit: int = 4,\n        exclude_domains: tuple[str, ...] = (),\n    ) -> list[str]:\n        """Rank a small learned-domain provider fallback set.\n\n        This preserves P2.5 targeted provider recovery without turning every warm\n        run into a search across all remembered stores. Sources already recovered\n        through structured/direct lanes are excluded by the caller; a temporarily\n        failed direct source remains eligible for fallback.\n        """\n        classification = classify_product(identity)\n        requested_category = str(classification.category or "GENERAL")\n        strong_category = classification.confidence >= 0.80 and requested_category != "GENERAL"\n        excluded = {_host(value) for value in exclude_domains if _host(value)}\n        now = datetime.now(timezone.utc)\n        ranked: list[tuple[float, str, str]] = []\n\n        for domain, raw in self._load().items():\n            row = dict(raw or {})\n            successes = int(row.get("success_count") or 0)\n            failures = int(row.get("failure_count") or 0)\n            if successes <= 0 or domain in excluded or row.get("price_capable") is False:\n                continue\n            categories = {str(value) for value in row.get("categories") or [] if str(value)}\n            if strong_category and categories and "GENERAL" not in categories and requested_category not in categories:\n                continue\n\n            total = successes + failures\n            success_rate = float(row.get("success_rate") if row.get("success_rate") is not None else (successes / total if total else 0.0))\n            health = float(row.get("health") if row.get("health") is not None else ((successes + 1) / (total + 2)))\n            score = (2.0 * success_rate) + health + min(successes, 3) * 0.25\n            if row.get("price_capable") is True:\n                score += 1.0\n            if row.get("extraction_methods"):\n                score += 0.25\n            if requested_category in categories:\n                score += 1.5\n            elif not categories or "GENERAL" in categories:\n                score += 0.25\n            last_success = str(row.get("last_success") or "")\n            if last_success:\n                try:\n                    observed = datetime.fromisoformat(last_success.replace("Z", "+00:00"))\n                    age_days = max(0.0, (now - observed.astimezone(timezone.utc)).total_seconds() / 86400.0)\n                    if age_days <= 30:\n                        score += 0.25\n                    elif age_days <= 90:\n                        score += 0.10\n                except (ValueError, TypeError):\n                    pass\n            ranked.append((score, last_success, domain))\n\n        ranked.sort(reverse=True)\n        return [domain for _score, _last, domain in ranked[: max(0, int(limit))]]\n\n'''
if "def provider_fallback_domains(" not in cap:
    if method_anchor not in cap:
        raise SystemExit("P8 bounded fallback patch abort: direct_candidates anchor missing")
    cap = cap.replace(method_anchor, method + method_anchor, 1)
CAP.write_text(cap, encoding="utf-8")

work = WORK.read_text(encoding="utf-8")
old_priority = "    priority_domains = tuple(capability_registry.successful_domains())\n"
if old_priority in work:
    work = work.replace(old_priority, "", 1)
elif "provider_fallback_domains(" not in work:
    raise SystemExit("P8 bounded fallback patch abort: old priority line missing")

old_direct = '''    if direct_capabilities:\n        emit(\n            "source_routing",\n            recovery_method="DIRECT_SOURCE",\n            candidates=len(direct_capabilities),\n            domains=[row.get("domain") for row in direct_capabilities],\n        )\n        offers.extend(_collect_direct_source_offers(\n            direct_capabilities,\n            working_identity,\n            emit,\n            trace=trace,\n            capability_registry=capability_registry,\n        ))\n    learned_sources = load_validated_source_urls(output_root, identity)\n'''
new_direct = '''    direct_rows: list[PriceOffer] = []\n    if direct_capabilities:\n        emit(\n            "source_routing",\n            recovery_method="DIRECT_SOURCE",\n            candidates=len(direct_capabilities),\n            domains=[row.get("domain") for row in direct_capabilities],\n        )\n        direct_rows = _collect_direct_source_offers(\n            direct_capabilities,\n            working_identity,\n            emit,\n            trace=trace,\n            capability_registry=capability_registry,\n        )\n        offers.extend(direct_rows)\n\n    direct_candidate_domains = {str(row.get("domain") or "").casefold().removeprefix("www.") for row in direct_capabilities}\n    direct_success_domains = {\n        (urlparse(row.url).hostname or "").casefold().removeprefix("www.")\n        for row in direct_rows\n        if (urlparse(row.url).hostname or "")\n    }\n    direct_success_domains = {\n        domain for domain in direct_success_domains\n        if domain in direct_candidate_domains or any(domain.endswith("." + candidate) for candidate in direct_candidate_domains)\n    }\n    provider_limit = max(1, min(4, max_sources // 12 or 1))\n    excluded_provider_domains = tuple(dict.fromkeys((*structured_domains, *sorted(direct_success_domains))))\n    failed_direct_domains = [\n        domain for domain in (str(row.get("domain") or "").casefold().removeprefix("www.") for row in direct_capabilities)\n        if domain and domain not in direct_success_domains and domain not in structured_domains\n    ]\n    ranked_provider_domains = capability_registry.provider_fallback_domains(\n        working_identity,\n        limit=provider_limit,\n        exclude_domains=excluded_provider_domains,\n    )\n    priority_domains = tuple(dict.fromkeys((*failed_direct_domains, *ranked_provider_domains)))[:provider_limit]\n    if priority_domains:\n        emit(\n            "source_routing",\n            recovery_method="LEARNED_PROVIDER_FALLBACK",\n            candidates=len(priority_domains),\n            domains=list(priority_domains),\n        )\n    learned_sources = load_validated_source_urls(output_root, identity)\n'''
if "recovery_method=\"LEARNED_PROVIDER_FALLBACK\"" not in work:
    if old_direct not in work:
        raise SystemExit("P8 bounded fallback patch abort: direct lane anchor missing")
    work = work.replace(old_direct, new_direct, 1)

WORK.write_text(work, encoding="utf-8")
print("P8_BOUNDED_PROVIDER_FALLBACK_PATCH=APPLIED")
