from enum import Enum

class ProviderStatus(str, Enum):
    EMPTY_KEY = "EMPTY_KEY"
    AUTH_REJECTED = "AUTH_REJECTED"
    TIMEOUT = "TIMEOUT"
    NETWORK_ERROR = "NETWORK_ERROR"
    QUOTA_OR_RATE_LIMIT = "QUOTA_OR_RATE_LIMIT"
    PROVIDER_ERROR = "PROVIDER_ERROR"
    INVALID_RESPONSE = "INVALID_RESPONSE"
    CONNECTED = "CONNECTED"
