from pathlib import Path

p=Path(__file__).resolve().parents[1]/'src/product_intelligence/batch.py'
s=p.read_text(encoding='utf-8')
old='''    candidates = [type("Candidate", (), {"url": item.source_url, "likely_official": True, "score": 1.0, "ai_assisted": False})()] if item.source_url else search_web(item.identity, limit=16)\n    if ai_config and ai_config.discovery_enabled and not any(bool(getattr(c,"likely_official",False)) for c in candidates):\n        ai_urls=discover_official_urls(item.identity,ai_config)\n        if ai_urls:\n            log(f"  IA web discovery: {len(ai_urls)} URLs candidatas; todas se validarán con el scraper")\n            known={getattr(c,"url","") for c in candidates}\n            for aic in ai_urls:\n                if aic.url in known: continue\n                candidates.append(type("Candidate",(),{"url":aic.url,"likely_official":False,"score":aic.confidence,"ai_assisted":True})())\n                known.add(aic.url)\n'''
new='''    candidates = [type("Candidate", (), {"url": item.source_url, "likely_official": True, "score": 1.0, "ai_assisted": False})()] if item.source_url else search_web(item.identity, limit=16)\n    preferred_country=(getattr(ai_config,"preferred_country","PE") or "PE").strip().lower() if ai_config else "pe"\n    def _preferred_region_candidate(c):\n        if not bool(getattr(c,"likely_official",False)):\n            return False\n        host=(urlparse(getattr(c,"url","")).hostname or "").lower()\n        return host.endswith("."+preferred_country) or ("."+preferred_country+".") in host\n    has_official=any(bool(getattr(c,"likely_official",False)) for c in candidates)\n    has_preferred_official=any(_preferred_region_candidate(c) for c in candidates)\n    needs_ai=bool(ai_config and ai_config.discovery_enabled and (not has_official or not has_preferred_official))\n    if needs_ai:\n        ai_urls=discover_official_urls(item.identity,ai_config)\n        if ai_urls:\n            log(f"  IA web discovery: {len(ai_urls)} URLs candidatas para mejorar fuente oficial/regional; todas se validarán con el scraper")\n            known={getattr(c,"url","") for c in candidates}\n            injected=[]\n            for aic in ai_urls:\n                if aic.url in known: continue\n                injected.append(type("Candidate",(),{"url":aic.url,"likely_official":False,"score":aic.confidence,"ai_assisted":True,"country":aic.country})())\n                known.add(aic.url)\n            injected.sort(key=lambda c:(str(getattr(c,"country","") or "").lower()!=preferred_country,-float(getattr(c,"score",0))))\n            candidates=injected+candidates\n'''
if old not in s:raise SystemExit('batch AI discovery anchor not found')
p.write_text(s.replace(old,new,1),encoding='utf-8')
print('regional AI discovery refined')
